### ISSUE TITLE
Cleanup use of YARP deprecated methods

### ISSUE THREAD

**Issue by traversaro** [robotology/event-driven#155]
YARP deprecated methods such as `asDouble` are used in the codebase, for example in https://github.com/robotology/yarp/pull/2833 . That code will not compile once https://github.com/robotology/yarp/pull/2833 is merged.

**Comment by arrenglover** [comment]
with the latest version of yarp it flags these deprecated messages, and may be an easy way to switch the methods. i.e. `asDouble()` changes to `asFloat64()` i believe

**Comment by traversaro** [comment]
Exactly!

**Comment by arrenglover** [comment]
#160 should have fixed all the warnings related to yarp. thanks for the heads up @traversaro
