### ISSUE TITLE
Help to check the event polarity from Gen3

### ISSUE THREAD

**Issue by LZC-68** [robotology/event-driven#165]
In the synthetic dataset, event polarity defines as:  

     Positive event: intensity increase, bool value: True
     Negative event: intensity decrease, bool value: False

But the event polarity definition of the collected dataset from Gen3 seems in the opposite way.

**Comment by arrenglover** [comment]
i've asked @mcasti-iit if he can check the encoding for the FPGA as well.

as mentioned the gen3 copies the value coming from the camera SDK
the zynqGrabber also just copies the value coming from the FPGA
