### ISSUE TITLE
upgrade Debian on Zynq

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [robotology/event-driven#19]
The current version of YARP does not support Debian 8.1 (currently installed on all of our Zynq devices).

We need to upgrade.

Which version? Ubuntu?

**Comment by arrenglover** [comment]
It might not be so easy as I think we use a custom version and kernel found here:
https://github.com/andreamerello/linux-zynq-stable

I don't know how easy it is to upgrade or change versions? @andreamerello @francescodiotalevi 

Otherwise a good idea.

**Comment by andreamerello** [comment]
As long as you update to a Debian filesystem that is designed for a kernel <= 4.9 you should be fine. Kernels are always backward compatible.

We don't have a more recent kernel for Zynq right now. Porting DMA patches (as well as other custom stuff) to newer kernels is planned (basically beacause of new UltraScale MPSoC), but it is a long-term task..

**Comment by andreamerello** [comment]
.. said that, upgrading Debian to a FS designed for a newer kernel, while keeping our Linux 4.9 might work.. In my experience it probably will.. But theoretically something might get broken..
