### ISSUE TITLE
branch `mapping` is stale

### ISSUE THREAD

**Issue by arrenglover** [robotology/event-driven#37]
the branch `mapping` has not been updated in 1 year, it should either be:
* removed if unneeded (but there are 98 commits ahead of master :warning: )
* updated and merged into devel
* taken the contents into an external repository which depends on `event-driven` as a library.

I think the 3rd option is correct. What do you think?

**Comment by Iaxama** [comment]
I will check

**Comment by arrenglover** [comment]
#40

**Comment by arrenglover** [comment]
branch deleted
