### ISSUE TITLE
BETA new branch "newSkinVisual" for (new) plotting of skin events opened

### ISSUE THREAD

**Issue by lucagl** [robotology/event-driven#41]
Problem: **need a reliable taxel address map for each skin patch**

To do (?)
- [x]  make a parent class for both skin events and samples
- [x] read from file taxel map instead of hardcoding it
- [x] draw contours of triangles
- [x] (major) make also an iso plot with time

**Comment by aikolina** [comment]
Closing since I made #78 to highlight the left issues.
