### ISSUE TITLE
python "event-collapse" does not process all data

### ISSUE THREAD

**Issue by arrenglover** [robotology/event-driven#45]
when using the event-collapse script the data file produced does not contain all the data in the original:

the file sizes are 275 mb compared to 1 mb.

the final timestamp is:
original: 19862 1572360436.827980
collapsed: 20956 1572360404.111330

looks like a strange bug as the collapsed bottle number is much larger than the original, but the original timestamp is 32 seconds later than the collapsed.

**Comment by Iaxama** [comment]
This bug is resolved by the pull request #44.

**Comment by arrenglover** [comment]
@Iaxama - thanks. I just thought of that. sorry.
