### ISSUE TITLE
undistortion remapping error

### ISSUE THREAD

**Issue by ghoshsuman** [robotology/event-driven#47]
Problems occurring when `undistort==true` for vPreProcess module:
* For stereo-rectification and undistortion, all event pixels get remapped to (0, 0).  

Dense shared projection: ![dense_shared](https://user-images.githubusercontent.com/35840258/68485753-1adbdb00-0240-11ea-9a07-af561b22780d.jpg)
Sparse shared projection:![sparse_shared](https://user-images.githubusercontent.com/35840258/68485830-36df7c80-0240-11ea-935b-815a4f80b09e.jpg)

* When [STEREO_DISPARITY] params are removed from **stefi_calib.ini** (i.e. doing only undistortion), vFramer (AE draw) crashes with segmentation fault. This is probably because vPreProcess remaps event pixels (using instrinsic parameters) in the output space of (608, 480) whereas vFramer expects events to be in (304, 240) space.

Sparse shared projection:![dense_shared](https://user-images.githubusercontent.com/35840258/68485928-64c4c100-0240-11ea-9ba3-20273b13da6f.jpg)
Sparse shared projection:![sparse_shared](https://user-images.githubusercontent.com/35840258/68485936-68584800-0240-11ea-8a80-175ecd6a768f.jpg)

I'm using input data and camera parameters from the ATIS cameras of the iCub robot, where the calibration was done using asymmetric grid of circles. The last time I saw it working using the same data and params was immediately before merging cmake_update changes into devel branch. There was some distortion at the corners due to poor calibration, but events were getting properly rectified nevertheless.

P.S. Switching left and right camera parameters produced the same problems

**Comment by arrenglover** [comment]
it seems like not all events are being mapped to 0 but most of them. The projected stereo looks terrible - i.e. only using a couple of hundred pixels between both the images. To me it seems like a poor calibration rather than a bug. I wonder if you can check the rectification results using the old method (i.e. roll back to before the new method was introduced?)

**Comment by ghoshsuman** [comment]
The current code seems to be working properly with the `undistort` flag. The calibration parameters I used above were faulty. A bug in the old code related to assignment of the image cv::Size vector during rectification transformation estimation somehow made those faulty parameters "work". Closing the issue.
