### ISSUE TITLE
event-driven in superbuild

### ISSUE THREAD

**Issue by arrenglover** [robotology/event-driven#60]
Any changes required to integrate event-driven into the superbuild need to be understood and updated.

**Comment by traversaro** [comment]
Hi @arrenglover, if you need any help on this feel free to ping me.

**Comment by arrenglover** [comment]
https://github.com/robotology/robotology-superbuild/pull/502

**Comment by traversaro** [comment]
Hi @arrenglover , if you could also do a recent release tag for event-driven so we use that in place of a fixed commit as done in https://github.com/robotology/robotology-superbuild/blob/master/releases/latest.releases.yaml#L173 it would be great.

**Comment by arrenglover** [comment]
FYI @traversaro I have made a new release tag v1.5 - https://github.com/robotology/event-driven/releases/tag/v1.5

**Comment by traversaro** [comment]
Thanks @arrenglover !
