### ISSUE TITLE
`binaryDumper` doesn't open when `cwd` longer than 50 characters

### ISSUE THREAD

**Issue by aikolina** [robotology/event-driven#62]
I couldn't run the `binaryDumper` correctly because my current working directory (cwd) was longer than `50` characters.

https://github.com/robotology/event-driven/blob/011be7ca1fd472a5175ac4013b7457619b93aa52/src/hardwareio/binaryDumper/binary-dumper.cpp#L65

I would put a bigger upper limit to avoid this issue.

**Comment by arrenglover** [comment]
#63 fixed this

**Comment by aikolina** [comment]
From PR #63, the default path is not anymore the current working directory but the $HOME directory. 

https://github.com/robotology/event-driven/blob/7355b26f72cf5daabbbb5e1a64cbe202693f7bba/src/hardwareio/binaryDumper/binary-dumper.cpp#L71
